### ISSUE TITLE
Sanitized ALPHABET

### ISSUE THREAD

**Issue by mrcook** [matiaskorhonen/radix62#2]
It would be very useful to sanitize the ALPHABET (b c d f g h j k l m n p q r s t v w x z 2 3 5 6 7 8 9) so that some of the more unsavoury words don't show up.

I know that isn't base62, but having that option would be good to have.

**Comment by matiaskorhonen** [comment]
Sounds like a good idea, but I think this is a feature that's beyond the scope of this library.

Also, if `9887532` encodes to something unsavoury in base 62, there's very little that can be done about it without compromising the very purpose of the library…
